services:
  bot:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5